name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip
          pip install -r app/requirements.txt
          pip install pbr  # bandit runtime dep
      - name: Lint & type
        run: |
          source .venv/bin/activate
          ruff check app/ scripts/ tests/
          mypy app/ --ignore-missing-imports --no-strict-optional || true
      - name: Tests
        env:
          SECRET_KEY: test-secret-12345678901234567890123456789012
          ADMIN_API_KEY: test-admin
          ML_API_KEY: test-ml
          READONLY_API_KEY: test-ro
          API_KEY_SALT: test-salt
          DATABASE_URL: sqlite:///ci.db
          REDIS_URL: redis://localhost:6379/0
        run: |
          source .venv/bin/activate
          pytest -q
      - name: Security - bandit
        run: |
          source .venv/bin/activate
          mkdir -p reports
          bandit -r app/ -f json -o reports/bandit.json --severity-level high || true
      - name: Security - safety
        run: |
          source .venv/bin/activate
          mkdir -p reports
          safety check --full-report | tee reports/safety-report.txt || true
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install & build & lint
        run: |
          npm ci
          npm run build
          npm run lint || true


