name: Simple Test Workflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-simple:
    name: Simple Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: '${{ runner.os }}-pip-'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r app/requirements.txt
    - name: Test basic functionality
      run: |
        echo "Testing basic functionality..."
        python3 -c "print('✅ Python is working')"
    - name: Test Flask import
      run: |
        echo "Testing Flask import..."
        cd app
        python3 -c "from main import create_app; print('✅ Flask import successful')"
    - name: Run basic pytest
      run: |
        echo "Running basic pytest..."
        python3 -m pytest tests/phase_1/ -v --tb=short

permissions:
  contents: read
  pull-requests: write
  issues: write
