name: Simple Test Workflow
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test-simple:
    name: Simple Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Install dependencies
      run: 'python3 -m pip install --upgrade pip

        pip3 install -r app/requirements.txt

        '
    - name: Test basic functionality
      run: "echo \"Testing basic functionality...\"\npython3 -c \"print('\u2705 Python\
        \ is working')\"\n"
    - name: Test Flask import
      run: "echo \"Testing Flask import...\"\ncd app\npython3 -c \"from main import\
        \ create_app; print('\u2705 Flask import successful')\"\n"
    - name: Run basic pytest
      run: 'echo "Running basic pytest..."

        python3 -m pytest tests/phase_1/ -v --tb=short

        '
permissions:
  contents: read
  pull-requests: write
  issues: write
'on':
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
